from core.base import LLM
from core.testing import Template
from openai import OpenAI
import json
import yaml
import os


class Grok(LLM):
    """
    An abstract class representing a Grok-based LLM from X.AI.

    Attributes:
        NAME (str): The name of the model.
        _CLIENT (OpenAI): The OpenAI client configured for X.AI.
        RESPONSE_FORMAT (str): The response format for the model.
        _PROMPTS (dict): A dictionary containing the system and user prompts.
    """

    def __init__(self, randomly_flip_options: bool = False, shuffle_answer_options: bool = False, agent_description: str | None = None):
        super().__init__(randomly_flip_options=randomly_flip_options, shuffle_answer_options=shuffle_answer_options)
        if "XAI_API_KEY" not in os.environ:
            raise ValueError(
                "Cannot access X.AI API due to missing API key. Please store your API key in environment variable 'XAI_API_KEY'."
            )
        self._CLIENT = OpenAI(
            api_key=os.environ["XAI_API_KEY"],
            base_url="https://api.x.ai/v1",
        )
        self.RESPONSE_FORMAT = "json_object"
        with open("./models/XAI/prompts.yml") as f:
            self._PROMPTS = yaml.safe_load(f)
        
        self.agent_description = agent_description

    def prompt(self, prompt: str, temperature: float = 0.7, seed: int = 42) -> str:
        """
        Generates a response to the provided prompt.
        
        Args:
            prompt (str): The prompt to generate a response for.
            temperature (float): The temperature value of the LLM.
            seed (int): The seed for controlling the LLM's output.
        
        Returns:
            str: The response generated by the LLM.
        """
        messages = []
        
        if self.agent_description:
            messages.append({"role": "system", "content": self.agent_description})
        
        messages.append({"role": "user", "content": prompt})
        
        response = self._CLIENT.chat.completions.create(
            model=self.NAME,
            temperature=temperature,
            seed=seed,
            messages=messages
        )

        return response.choices[0].message.content

    def populate(self, control: Template, treatment: Template, scenario: str, temperature: float = 0.7, seed: int = 42) -> tuple[Template, Template]:
        """
        Populates the blanks in the provided control and treatment templates according to the scenario.
        
        Args:
            control (Template): The control template to populate.
            treatment (Template): The treatment template to populate.
            scenario (str): A string describing the scenario for the population.
            temperature (float): The temperature value of the LLM.
            seed (int): The seed for controlling the LLM's output.
            
        Returns:
            tuple[Template, Template]: The populated control and treatment Template objects.
        """
        if control is not None and len(control.get_gaps()) > 0:
            control = self._populate(control, scenario, temperature=temperature, seed=seed)

        if control is not None and treatment is not None:
            insertions = control.get_insertions(origin='model')
            treatment.insert(insertions=insertions)

        if treatment is not None and len(treatment.get_gaps()) > 0:
            treatment = self._populate(treatment, scenario, temperature=temperature, seed=seed)

        return control, treatment

    def _define_response_format(self, mode: str, gaps: list[str]) -> object:
        """
        Defines the response format for controlled model outputs.

        Args:
            mode (str): The mode for controlling outputs, either "json_schema" (for Structured Outputs) or "json_object" (for JSON Mode).
            gaps (list[str]): A list of gaps in the template that need to be filled.

        Returns:
            object: An object describing the response format.
        """
        
        if mode == "json_schema":
            response_format = {
                "type": "json_object"
            }
        elif mode == "json_object":
            response_format = {
                "type": "json_object"
            }
        else:
            response_format = None

        return response_format

    def _populate(self, template: Template, scenario: str, temperature: float = 0.7, seed: int = 42) -> Template:
        """
        Populates the blanks in the provided template according to the scenario.
        
        Args:
            template (Template): The template to populate.
            scenario (str): A string describing the scenario/context for the population.
            temperature (float): The temperature value of the LLM.
            seed (int): The seed for controlling the LLM's output.

        Returns:
            Template: The populated Template object.
        """

        system_prompt = self._PROMPTS['system_prompt']
        user_prompt = self._PROMPTS['population_prompt']

        gaps = template.get_gaps(origin='model')
        gaps_format = [f"    \"{gap}\": \"...\"" for gap in gaps]
        expected_format = "{\n" + ',\n'.join(gaps_format) + "\n}"

        response_format = self._define_response_format(self.RESPONSE_FORMAT, gaps)

        user_prompt = user_prompt.replace("{{scenario}}", scenario)
        user_prompt = user_prompt.replace("{{template}}", template.format())
        user_prompt = user_prompt.replace("{{format}}", expected_format)

        messages = []
        
        if self.agent_description:
            messages.append({"role": "system", "content": self.agent_description})
        else:
            messages.append({"role": "system", "content": system_prompt})
            
        messages.append({"role": "user", "content": user_prompt})

        response = self._CLIENT.chat.completions.create(
            model=self.NAME,
            temperature=temperature,
            seed=seed,
            response_format=response_format,
            messages=messages
        )

        insertions = json.loads(response.choices[0].message.content)
        insertions = self._fix_insertions(insertions)

        self._validate_population(template, insertions, response.choices[0].message.content)

        for pattern in insertions.keys():
            template.insert(pattern, insertions[pattern], 'model')

        return template

    def _fix_insertions(self, insertions: dict) -> dict:
        """
        Ensures all keys in the dictionary start with [[ and end with ]].
        
        Args:
            insertions (dict): The dictionary to format keys for.

        Returns:
            dict: A new dictionary with formatted keys.
        """

        fixed_insertions = {}

        for key, value in insertions.items():
            if not key.startswith('[['):
                key = '[[' + key
            if not key.endswith(']]'):
                key = key + ']]'
            
            fixed_insertions[key] = value
        
        return fixed_insertions


class GrokThree(Grok):
    """
    A class representing a Grok-3 LLM from X.AI.

    Attributes:
        NAME (str): The name of the model.
        agent_description (str): Optional description of the agent persona.
    """

    def __init__(self, randomly_flip_options: bool = False, shuffle_answer_options: bool = False, agent_description: str | None = None):
        super().__init__(randomly_flip_options=randomly_flip_options, shuffle_answer_options=shuffle_answer_options, agent_description=agent_description)
        self.NAME = "grok-3-latest"
